---
- name: Make sure APT cache is updated
  apt:
    update_cache: true
    cache_valid_time: 1800

- name: Install dependencies
  apt:
    state: present
    name:
      - ca-certificates
      - curl
      - gnupg

- name: Add GPG key
  apt_key:
    state: present
    url: "{{ docker_gpg_key_url }}/{{ ansible_distribution | lower }}/gpg"

- name: Add Docker repository
  apt_repository:
    repo: >
      deb [arch={{ ansible_architecture }}
      signed-by=/etc/apt/keyrings/docker.gpg]
      {{ docker_repo_base_url }}/{{ ansible_distribution | lower }}
      {{ ansible_distribution_release }} stable
    state: present

- name: Make sure APT cache is updated
  apt:
    update_cache: true

- name: Install Docker
  apt:
    state: present
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
